use crate::w3c_parser::{W3CToken, W3CTokenType, W3CTokenValue};

/// Generator for TypeScript type definitions from W3C Design Tokens.
pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    /// Generate TypeScript code from W3C tokens.
    pub fn generate(tokens: &[W3CToken]) -> String {
        let mut output = String::with_capacity(tokens.len() * 200);

        // File header
        output.push_str("// Generated by Euis TypeScript Generator\n\n");

        // Generate token paths union type
        output.push_str(&Self::generate_token_paths_type(tokens));
        output.push('\n');

        // Generate token values type
        output.push_str(&Self::generate_token_values_type(tokens));
        output.push('\n');

        // Generate tokens object
        output.push_str(&Self::generate_tokens_object(tokens));
        output.push('\n');

        // Generate helper types
        output.push_str(&Self::generate_helper_types());

        output
    }

    /// Generate a union type of all token paths.
    fn generate_token_paths_type(tokens: &[W3CToken]) -> String {
        let mut output = String::from("/** Union type of all token paths */\n");
        output.push_str("export type TokenPath =\n");

        for (i, token) in tokens.iter().enumerate() {
            if i == 0 {
                output.push_str(&format!("  | '{}'\n", token.path));
            } else {
                output.push_str(&format!("  | '{}'\n", token.path));
            }
        }

        output.push_str(";\n");
        output
    }

    /// Generate a type mapping token paths to their values.
    fn generate_token_values_type(tokens: &[W3CToken]) -> String {
        let mut output = String::from("/** Map of token paths to their value types */\n");
        output.push_str("export interface TokenValues {\n");

        for token in tokens {
            let value_type = Self::get_typescript_type_for_token(token);
            output.push_str(&format!("  '{}': {};\n", token.path, value_type));
        }

        output.push_str("}\n");
        output
    }

    /// Generate the tokens object with const assertions.
    fn generate_tokens_object(tokens: &[W3CToken]) -> String {
        let mut output = String::from("/** Design tokens with type safety */\n");
        output.push_str("export const tokens = {\n");

        for token in tokens {
            let value_str = Self::token_value_to_typescript(&token.value);
            output.push_str(&format!("  '{}': {} as const,\n", token.path, value_str));
        }

        output.push_str("} as const;\n");
        output
    }

    /// Generate helper types for working with tokens.
    fn generate_helper_types() -> String {
        r#"/** Extract value type for a specific token path */
export type TokenValue<T extends TokenPath> = TokenValues[T];

/** Get a token value with type safety */
export function getToken<T extends TokenPath>(path: T): TokenValue<T> {
  return tokens[path] as TokenValue<T>;
}

/** Check if a token exists */
export function hasToken(path: string): path is TokenPath {
  return path in tokens;
}
"#.to_string()
    }

    /// Get the TypeScript type for a token.
    fn get_typescript_type_for_token(token: &W3CToken) -> String {
        match &token.token_type {
            Some(W3CTokenType::Color) => "string".to_string(),
            Some(W3CTokenType::Dimension) => "string".to_string(),
            Some(W3CTokenType::FontFamily) => "string".to_string(),
            Some(W3CTokenType::FontWeight) => "number | string".to_string(),
            Some(W3CTokenType::Duration) => "string".to_string(),
            Some(W3CTokenType::CubicBezier) => "string".to_string(),
            Some(W3CTokenType::Number) => "number".to_string(),
            Some(W3CTokenType::StrokeStyle) => "string".to_string(),
            _ => "unknown".to_string(),
        }
    }

    /// Convert a token value to TypeScript literal.
    fn token_value_to_typescript(value: &W3CTokenValue) -> String {
        match value {
            W3CTokenValue::Literal(s) => format!("'{}'", s.replace('\'', "\\'")),
            W3CTokenValue::Reference(r) => format!("'{{{{{}}}}}'", r),
            W3CTokenValue::Composite(map) => {
                let entries: Vec<String> = map.iter()
                    .map(|(k, v)| format!("{}: {}", k, Self::token_value_to_typescript(v)))
                    .collect();
                format!("{{ {} }}", entries.join(", "))
            }
        }
    }

    /// Generate CSS custom properties type.
    pub fn generate_css_properties_type(tokens: &[W3CToken]) -> String {
        let mut output = String::from("/** CSS custom property names */\n");
        output.push_str("export type CSSCustomProperty =\n");

        for token in tokens {
            let css_var = format!("--{}", token.path.replace('.', "-"));
            output.push_str(&format!("  | '{}'\n", css_var));
        }

        output.push_str(";\n");
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_token(path: &str, value: &str, token_type: W3CTokenType) -> W3CToken {
        W3CToken {
            path: path.to_string(),
            value: W3CTokenValue::Literal(value.to_string()),
            token_type: Some(token_type),
            description: None,
        }
    }

    #[test]
    fn test_generate_typescript() {
        let tokens = vec![
            create_token("color.primary", "#3b82f6", W3CTokenType::Color),
            create_token("spacing.base", "16px", W3CTokenType::Dimension),
        ];

        let ts = TypeScriptGenerator::generate(&tokens);
        
        assert!(ts.contains("export type TokenPath"));
        assert!(ts.contains("export interface TokenValues"));
        assert!(ts.contains("export const tokens"));
        assert!(ts.contains("'color.primary'"));
        assert!(ts.contains("'spacing.base'"));
    }

    #[test]
    fn test_generate_css_properties_type() {
        let tokens = vec![
            create_token("color.primary", "#3b82f6", W3CTokenType::Color),
        ];

        let ts = TypeScriptGenerator::generate_css_properties_type(&tokens);
        
        assert!(ts.contains("--color-primary"));
        assert!(ts.contains("CSSCustomProperty"));
    }

    #[test]
    fn test_get_typescript_type() {
        let color_token = create_token("color.primary", "#3b82f6", W3CTokenType::Color);
        assert_eq!(TypeScriptGenerator::get_typescript_type_for_token(&color_token), "string");

        let number_token = create_token("opacity.default", "0.5", W3CTokenType::Number);
        assert_eq!(TypeScriptGenerator::get_typescript_type_for_token(&number_token), "number");
    }
}
